const agPtBr = {     
    // Set Filter
    selectAll: 'Selecionar tudo',
    selectAllSearchResults: 'Selecionar todos os resultados da pesquisa',
    searchOoo: 'Procurar...',
    blanks: 'Espaços em branco',
    noMatches: 'Sem combinações.',

    // Number Filter & Text Filter
    filterOoo: 'Filtro...',
    equals: 'É igual a',
    notEqual: 'Não igual',

    // Number Filter
    lessThan: 'Menor que',
    greaterThan: 'Maior que',
    lessThanOrEqual: 'Menor ou igual',
    greaterThanOrEqual: 'Maior que ou igual',
    inRange: 'Dentro do alcance',
    inRangeStart: 'Para',
    inRangeEnd: 'De',

    // Text Filter
    contains: 'Contém',
    notContains: 'Não contém',
    startsWith: 'Começa com',
    endsWith: 'Termina comom',

    // Date Filter
    dateFormatOoo: 'dd-mm-Yyyy',

    // Filter Conditions
    andCondition: 'E',
    orCondition: 'OU',

    // Filter Buttons
    applyFilter: 'Aplique',
    resetFilter: 'Redefinir',
    clearFilter: 'Claro',
    cancelFilter: 'Cancelar',    
   
    // Side Bar
    columns: 'Colunas',
    filters: 'Filtros',
    
    // columns tool panel
    pivotMode: 'Modo Pivô',    
    groups: 'Grupos de linhas',
    rowGroupColumnsEmptyMessage: 'Arraste aqui para definir grupos de linhas',    
    values: 'Valores',    
    valueColumnsEmptyMessage: 'Arraste aqui para agregar',   
    pivots: 'Etiquetas da colunacoluna',
    pivotColumnsEmptyMessage: 'Arraste aqui para definir os rótulos das colunas',    

    // Header of the Default Group Column
    group: 'Group',
    
    // Other
    loadingOoo: 'Carregando...',
    noRowsToShow: 'Não há linhas para mostrar',
    enabled: 'ativado',

    // Menu
    pinColumn: 'Coluna de pinos',
    pinLeft: 'Fixar à esquerda',
    pinRight: 'Fixar à direita',
    noPin: 'No Pin',
    valueAggregation: 'Agregação de Valor',
    autosizeThiscolumn: 'Redimensionar automaticamente esta coluna',
    autosizeAllColumns: 'Redimensionar automaticamente todas as colunas',
    groupBy: 'Agrupar por',
    ungroupBy: 'Desagrupar por',
    resetColumns: 'Reset columns',
    expandAll: 'Expandir todosodos',
    collapseAll: 'Feche tudo',
    copy: 'cópia de',
    ctrlC: 'Ctrl+C',
    copyWithHeaders: 'Copiar com cabeçalhos',    
    paste: 'Colar',
    ctrlV: 'Ctrl+V',
    export: 'Exportar',
    csvExport: 'Exportação de CSV',
    excelExport: 'Exportação Excel (.xlsx)',
    excelXmlExport: 'Exportação Excel (.xml)',

    // Enterprise Menu Aggregation and Status Bar
    sum: 'Soma',
    min: 'Mín.',
    max: 'Máx.',
    none: 'Nenhum',
    count: 'Contagem',
    avg: 'Média',
    filteredRows: 'Filtrado',
    selectedRows: 'Selecionado',
    totalRows: 'Total de linhasinhas',
    totalAndFilteredRows: 'Linhas',
    page: 'Página',
    more: 'Mais',
    to: 'para',
    of: 'de',
    next: 'Próximo',
    last: 'Último',
    first: 'Primeiro',
    previous: 'Anterior', 

    // Enterprise Menu (Charts)
    pivotChartAndPivotMode: 'Gráfico Dinâmico e Modo Dinâmico',
    pivotChart: 'Gráfico Dinâmico',
    chartRange: 'Intervalo do gráfico',     

    columnChart: 'Coluna',
    groupedColumn: 'Agrupados',
    stackedColumn: 'Empilhadosdos',
    normalizedColumn: '100% empilhado',

    barChart: 'Barra',
    groupedBar: 'Agrupados',
    stackedBar: 'Empilhados',
    normalizedBar: '100% empilhado',

    pieChart: 'Pizza',
    pie: 'Pizza',
    doughnut: 'Rosquinha',

    line: 'Linha',

    xyChart: 'X Y (Dispersão)',
    scatter: 'Dispersão',
    bubble: 'Bolha',

    areaChart: 'Área',
    area: 'Área',
    stackedArea: 'Empilhados',
    normalizedArea: '100% empilhado',

    histogramChart: 'Histograma',

    // Charts
    pivotChartTitle: 'Gráfico Dinâmico',
    rangeChartTitle: 'Gráfico de Gama',
    settings: 'Configurações',
    data: 'Dados',
    format: 'Formatoo',
    categories: 'Categorias',
    defaultCategory: '(Nenhum)',
    series: 'Series',
    xyValues: 'X Y Valores',
    paired: 'Modo emparelhado',
    axis: 'Eixo',
    navigator: 'Navegador',
    color: 'Cor',
    thickness: 'Espessura',
    xType: 'X Tipo',
    automatic: 'Automáticoo',
    category: 'Categoriaa',
    number: 'Número',
    time: 'Tempo',
    xRotation: 'X Rotação',
    yRotation: 'Y Rotação',
    ticks: 'Ticks',
    width: 'Largura',
    height: 'Altura',
    length: 'comprimento',
    padding: 'Preenchimento',
    spacing: 'Espaçamento',
    chart: 'Gráficococo',
    title: 'Título',
    titlePlaceholder: 'Título do gráfico - clique duas vezes para editar',
    background: 'fundo',
    font: 'Fonte',
    top: 'Topo',
    right: 'Direita',
    bottom: 'Inferior',
    left: 'Esquerda',
    labels: 'Etiquetas',
    size: 'Tamanho',
    minSize: 'Tamanho mínimo',
    maxSize: 'Tamanho máximo',
    legend: 'lenda',
    position: 'Posição',
    markerSize: 'Tamanho do marcador',
    markerStroke: 'Curso do marcador',
    markerPadding: 'Marcador de preenchimento',
    itemSpacing: 'Espaçamento entre itens',
    itemPaddingX: 'Preenchimento do item Xdo item X',
    itemPaddingY: 'Preenchimento do item Y',
    layoutHorizontalSpacing: 'Espaçamento Horizontal',
    layoutVerticalSpacing: 'Espaçamento vertical',
    strokeWidth: 'Largura do traçado',
    offset: 'Deslocamento',
    offsets: 'Deslocamentos',
    tooltips: 'Dicas de ferramentas',
    callout: 'Chamar',
    markers: 'Marcadores',
    shadow: 'Sombra',
    blur: 'Borrão',
    xOffset: 'Deslocamento X',
    yOffset: 'Deslocamento Y',
    lineWidth: 'Espessura da linha',
    normal: 'Normal',
    bold: 'Negrito',
    italic: 'itálico',
    boldItalic: 'Negrito itálico',
    predefined: 'Predefinido',
    fillOpacity: 'Opacidade de preenchimento',
    strokeOpacity: 'Opacidade da linha',
    histogramBinCount: 'Contagem de bin',
    columnGroup: 'Coluna',
    barGroup: 'Barra',
    pieGroup: 'Pizza',
    lineGroup: 'Linha',
    scatterGroup: 'X Y (Dispersão)',
    areaGroup: 'Área',
    histogramGroup: 'Histogramaa',
    groupedColumnTooltip: 'Agrupados',
    stackedColumnTooltip: 'Empilhados',
    normalizedColumnTooltip: '100% empilhado',
    groupedBarTooltip: 'Agrupados',
    stackedBarTooltip: 'Empilhados',
    normalizedBarTooltip: '100% empilhado',
    pieTooltip: 'Pizza',
    doughnutTooltip: 'Rosquinha',
    lineTooltip: 'Linha',
    groupedAreaTooltip: 'Área',
    stackedAreaTooltip: 'Empilhados',
    normalizedAreaTooltip: '100% empilhado',
    scatterTooltip: 'Dispersão',
    bubbleTooltip: 'Bolha',
    histogramTooltip: 'Histograma',
    noDataToChart: 'Não há dados disponíveis para serem mapeados.rem mapeados.',
    pivotChartRequiresPivotMode: 'O Gráfico Dinâmico requer o Modo Dinâmico ativado.',
}

export default agPtBr